import math

N = int(input())
L = int(input())

for x in range(L):
    r = math.sin(x * ((2 * math.pi * N) / L ))
    rplus = ((r + 1) / 2) * 40
    rplusrounded = round(rplus)
    print('X' * rplusrounded)



""" 
Sample output 1

XXXXXXXXXXXXXXXXXXXX 20
XXXXXXXXXXXXXXXXXXXXXXXXXX 26
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 32
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 36
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 39
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 40
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 39
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 36
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 32
XXXXXXXXXXXXXXXXXXXXXXXXXX 26
XXXXXXXXXXXXXXXXXXXX 20
XXXXXXXXXXXXXX 14
XXXXXXXX 8
XXXX 4
X 1
 0
X 1
XXXX 4
XXXXXXXX 8
XXXXXXXXXXXXXX 14

Sample output 2

XXXXXXXXXXXXXXXXXXXX 20
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 37
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXX
XXX
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXX
XXX

"""